# Disable some built-in rules
config:
  descriptive-link-text: false
  line-length: false
  no-alt-text: false
  no-inline-html: false
  no-bare-urls: false
  code-block-style: false

# Ignore system files
ignores:
  - "**/.DS_Store"
