name: CI

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm clean-install --progress=false --no-fund

    - name: Build Site
      run: npm run build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm clean-install --progress=false --no-fund

    - name: Lint JavaScript
      run: npm run lint

  lint-html:
    name: Lint HTML
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies
      run: npm clean-install --progress=false --no-fund

    - name: Build
      run: npm run build

    - name: Lint HTML
      run: npm run lint:html
